import {test,expect,type Page} from '@playwright/test';
import {readFileSync,readdirSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
const password='Healthcare-browser-password-2026';
function clearLimits(){const db=new DatabaseSync('.data/e2e/mediq.sqlite');db.exec('DELETE FROM rate_limits');db.close();}
test.beforeEach(clearLimits);
async function skip(page:Page){const button=page.getByRole('button',{name:'Skip tour',exact:true});if(await button.first().isVisible())await button.first().click();}
async function visit(page:Page,path='/find'){await page.goto(path);await expect(page.locator('main')).toBeVisible();await skip(page);}
async function signup(page:Page,email:string,firstName='Avery'){await visit(page,'/signup');await page.getByLabel('First name',{exact:true}).fill(firstName);await page.getByLabel('Last name',{exact:true}).fill('Tester');await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Create a free account',exact:true}).click();await expect(page).toHaveURL(/verify/);const otp=()=>readdirSync('.data/e2e/mail').map(file=>JSON.parse(readFileSync('.data/e2e/mail/'+file,'utf8'))).find(mail=>mail.to===email)?.otp;await expect.poll(otp).toBeTruthy();await page.getByLabel('Verification code').fill(otp());await page.getByRole('button',{name:'Verify your email',exact:true}).click();await expect(page).toHaveURL(/find/);}
async function selectTime(page:Page,label:string,hour:string,minute:string,period?:string){const picker=page.getByRole('group',{name:label,exact:true});await picker.getByRole('combobox',{name:label+' hour',exact:true}).selectOption(hour);await picker.getByRole('combobox',{name:label+' minute',exact:true}).selectOption(minute);if(period)await picker.getByRole('combobox',{name:label+' AM/PM',exact:true}).selectOption(period);}
test('homepage search above the fold, guest navigation, footer and old/new routes',async({page})=>{
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:width<500?667:900});await visit(page,'/');const find=page.getByRole('button',{name:'Find Care',exact:true});expect((await find.boundingBox())!.y+(await find.boundingBox())!.height).toBeLessThan(width<500?667:900);await expect(page.getByText('MediQ is not an emergency service. For life-threatening symptoms, call 911 or go to the nearest emergency department.',{exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Log in / Sign up'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);}
 await page.setViewportSize({width:1440,height:900});await page.getByLabel('Location',{exact:true}).fill('27701');await page.getByLabel('What kind of care are you looking for?',{exact:true}).selectOption('Urgent care');await page.getByRole('button',{name:'Find Care',exact:true}).click();await skip(page);await expect(page.locator('.clinic-card')).toHaveCount(1);await expect(page.locator('.clinic-card')).toContainText('Brightwell');await expect(page.getByText('MediQ does not diagnose conditions or determine emergencies. Search helps you find relevant care.',{exact:true})).toBeVisible();
 const nav=page.getByRole('navigation',{name:'Primary navigation'});await expect(nav.getByRole('link')).toHaveText(['Find Care','Appointments','Report a Wait','About']);for(const label of ['Contact Us','Privacy','Safety','Accessibility'])await expect(page.getByRole('navigation',{name:'Footer navigation'}).getByRole('link',{name:label,exact:true})).toBeVisible();
 for(const path of ['/saved','/appointments','/know','/about','/privacy','/safety','/accessibility','/know#privacy','/know#safety']){await visit(page,path);await expect(page.locator('h1')).toBeVisible();}
 await visit(page,'/saved');await expect(page.getByRole('heading',{name:'No visits are saved'})).toBeVisible();await expect(page.locator('.appointment-list')).toHaveCount(0);
 await page.setViewportSize({width:320,height:667});await expect(page.getByRole('navigation',{name:'Mobile navigation'}).getByRole('link')).toHaveText(['Find Care','Appointments','Report a Wait','About']);
});
test('verified signup tour is immediate and server-persisted; account menu supports long names and returning login',async({page,browser})=>{
 const email=`healthcare-tour-${Date.now()}@example.test`,name='Avery'.repeat(14);await signup(page,email,name);await expect(page.getByRole('dialog',{name:'Product tour'})).toBeVisible();await page.keyboard.press('Tab');expect(await page.evaluate(()=>!!document.activeElement?.closest('dialog'))).toBe(true);await page.getByRole('button',{name:'Skip tour',exact:true}).click();await expect.poll(async()=>{const response=await page.request.get('/api/me');return (await response.json()).tourState;}).toBe('complete');
 const summary=page.locator('.account-menu summary');await expect(summary).toHaveText('Hello, '+name+' ▾');expect(await summary.evaluate(element=>{const child=element.firstElementChild!;return child.scrollWidth>child.clientWidth;})).toBe(true);await summary.click();await expect(page.getByRole('link',{name:'Settings',exact:true})).toBeVisible();await page.keyboard.press('Escape');await expect(summary).toBeFocused();await expect(page.locator('.account-menu')).not.toHaveAttribute('open','');
 const other=await browser.newContext();const device=await other.newPage();await visit(device,'/login');await device.getByLabel('Email',{exact:true}).fill(email);await device.getByLabel('Password',{exact:true}).fill(password);await device.getByRole('button',{name:'Sign in',exact:true}).click();await expect(device).toHaveURL(/find/);await expect(device.locator('.clinic-card').first()).toBeVisible();await expect(device.getByRole('dialog',{name:'Product tour'})).toHaveCount(0);await device.locator('.account-menu summary').click();await device.locator('.account-menu-panel').getByRole('button',{name:'Product tour',exact:true}).click();await expect(device.getByRole('dialog',{name:'Product tour'})).toBeVisible();await device.keyboard.press('Escape');await other.close();
});
test('stage label/time pairing, colors, evidence, keyboard explanations, RTL and long translations at all widths',async({page})=>{
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});await visit(page,'/clinic/brightwell-urgent-care');for(const locale of ['en','pl','ar','gu','hi','zh','es']){await page.locator('.language-control select').selectOption(locale);const pairs=page.locator('.visit-breakdown .stage-pair');await expect(pairs).toHaveCount(4);for(const pair of await pairs.all()){await expect(pair.locator('strong')).toBeVisible();const size=await pair.boundingBox();const value=await pair.locator('strong').boundingBox();expect(value!.x).toBeGreaterThanOrEqual(size!.x);expect(value!.x+value!.width).toBeLessThanOrEqual(size!.x+size!.width+1);expect(await pair.getAttribute('aria-label')).toBeTruthy();}const patterns=await page.locator('.stage-bar span').evaluateAll(nodes=>nodes.map(node=>getComputedStyle(node).backgroundImage));expect(new Set(patterns).size).toBe(4);const colors=await pairs.evaluateAll(nodes=>nodes.map(node=>getComputedStyle(node).backgroundColor));expect(new Set(colors).size).toBe(4);expect(colors[1]).toBe('rgb(255, 226, 77)');expect(colors[2]).toBe('rgb(56, 217, 119)');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);}await page.screenshot({path:`test-results/healthcare-stages-${width}.png`,fullPage:true});}
 await page.locator('.language-control select').selectOption('en');const help=page.locator('.concept-help').filter({has:page.getByText('About visit estimates',{exact:true})}).first();await help.locator('summary').focus();await page.keyboard.press('Enter');await expect(help.locator('p')).toBeVisible();await page.keyboard.press('Enter');await expect(help.locator('p')).not.toBeVisible();await expect(page.locator('.estimate-evidence')).toContainText('Fictional reference model');await expect(page.locator('.estimate-evidence')).toContainText('Not enough recent evidence');await expect(page.locator('.clinic-accessibility')).toContainText('Unknown');await expect(page.locator('.insurance-notice')).toHaveText('Please confirm coverage with your insurer and clinic.');
 await page.emulateMedia({reducedMotion:'reduce'});expect(await page.evaluate(()=>getComputedStyle(document.documentElement).scrollBehavior)).toBe('auto');
});
test('strict accessibility combinations, unknown exclusion and stable urgent machine values',async({page})=>{
 await visit(page);await page.getByLabel('Wheelchair accessibility',{exact:true}).check();await expect(page.locator('.clinic-card')).toHaveCount(2);await page.getByLabel('Accessible restroom',{exact:true}).check();await expect(page.locator('.clinic-card')).toHaveCount(2);await page.getByLabel('Accepted insurance',{exact:true}).selectOption('Medicaid');await page.getByRole('radio',{name:'Urgent Care',exact:true}).check();await expect(page.locator('.clinic-card')).toHaveCount(1);await expect(page.getByRole('radio',{name:'Urgent Care',exact:true})).toHaveAttribute('name','visit-mode');const result=await page.request.get('/api/clinics?filters='+encodeURIComponent(JSON.stringify({accessibility:['wheelchair'],visitMode:'urgent'})));expect((await result.json())[0].estimates.some((estimate:any)=>estimate.mode==='urgent')).toBe(true);await page.getByLabel('ASL interpretation',{exact:true}).check();await expect(page.getByText('No clinics match everything yet',{exact:true})).toBeVisible();
});
test('full reports use dropdown times, handle midnight and accept optional unknowns; ongoing reports never become totals',async({page})=>{
 await visit(page,'/report?clinic=brightwell-urgent-care');await expect(page.getByRole('radio',{name:/I'm here now/})).toBeVisible();await expect(page.getByRole('radio',{name:/I already finished my visit/})).toBeVisible();await expect(page.locator('input[type=time],input[type=datetime-local]')).toHaveCount(0);const day=new Date(Date.now()-2*86400000).toISOString().slice(0,10);await page.getByLabel('Visit date',{exact:true}).fill(day);await selectTime(page,'Arrived','11','30','pm');await selectTime(page,'Check out complete','12','30','am');await page.getByRole('button',{name:'Submit report',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Select next day');await page.getByLabel('Departure was on the next day').check();await page.getByRole('button',{name:'Submit report',exact:true}).click();await expect(page.getByRole('heading',{name:'That’s one more useful signal.'})).toBeVisible();await expect(page.locator('.confirmation-summary')).toContainText('60');
 await visit(page,'/clinic/brightwell-urgent-care');await expect(page.locator('.report-feed')).toContainText('Visit type unknown');await visit(page,'/report?clinic=brightwell-urgent-care');await page.getByRole('radio',{name:/I'm here now/}).check();await page.getByLabel('Minutes waiting so far',{exact:true}).fill('19');await page.getByRole('button',{name:'Submit report',exact:true}).click();await expect(page.locator('.confirmation-summary')).toContainText('Minutes waiting so far');const db=new DatabaseSync('.data/e2e/mediq.sqlite');const row=db.prepare("SELECT total_minutes,elapsed_minutes,mode FROM reports WHERE kind='current-wait' AND elapsed_minutes=19").get();expect(row?.total_minutes).toBeNull();expect(row?.mode).toBeNull();db.close();
});
test('imperial dropdowns preserve canonical metric values across repeated saves and can clear optional data',async({page})=>{
 await signup(page,`healthcare-settings-${Date.now()}@example.test`);await expect(page.getByRole('dialog',{name:'Product tour'})).toBeVisible();await skip(page);await visit(page,'/settings');await expect(page.getByLabel('Gender',{exact:true})).toHaveCount(0);for(const label of ['Sex','Weight (lb)','Height (ft and in)','Age (years)']){await expect(page.getByLabel(label,{exact:true})).toHaveValue('');expect(await page.getByLabel(label,{exact:true}).evaluate(node=>node.tagName)).toBe('SELECT');}await page.getByLabel('Weight (lb)',{exact:true}).selectOption('154');await page.getByLabel('Height (ft and in)',{exact:true}).selectOption('69');await page.getByRole('button',{name:'Save settings',exact:true}).click();await expect(page.getByText('Settings saved.',{exact:true})).toBeVisible();let response=await page.request.get('/api/me');const profile=(await response.json()).profile;expect(profile.weightKg).toBeCloseTo(69.85322498,8);expect(profile.heightCm).toBe(175.26);await page.reload();for(let i=0;i<2;i++){await page.getByRole('button',{name:'Save settings',exact:true}).click();response=await page.request.get('/api/me');expect((await response.json()).profile.weightKg).toBe(profile.weightKg);}for(const weightKg of [1,650]){const res=await page.request.put('/api/profile',{headers:{origin:'http://localhost:4173'},data:{...profile,firstName:'Avery',lastName:'Tester',weightKg,heightCm:175.234567}});expect(res.ok()).toBe(true);await page.reload();await expect(page.getByLabel('Weight (lb)',{exact:true})).toHaveValue(weightKg===1?'2':'1433');await page.getByRole('button',{name:'Save settings',exact:true}).click();await expect.poll(async()=>{const res=await page.request.get('/api/me');return (await res.json()).profile.weightKg;}).toBe(weightKg);const current=await page.request.get('/api/me');expect((await current.json()).profile.heightCm).toBe(175.234567);}
 await page.getByRole('button',{name:'Clear optional fields',exact:true}).click();await page.getByRole('button',{name:'Save settings',exact:true}).click();await expect.poll(async()=>{const res=await page.request.get('/api/me');return (await res.json()).profile.weightKg;}).toBeNull();
});
test('accessibility page and feedback path work; language-specific dropdown clocks and translated new pages',async({page})=>{
 await visit(page,'/accessibility');await page.getByRole('link',{name:'Report an accessibility issue',exact:true}).click();await page.getByLabel('Accessibility feedback',{exact:true}).fill('The keyboard focus on the care page could be easier to see.');await page.getByRole('button',{name:'Send accessibility feedback'}).click();await expect(page.getByText('Accessibility feedback received. Thank you.',{exact:true})).toBeVisible();const db=new DatabaseSync('.data/e2e/mediq.sqlite');expect(db.prepare('SELECT count(*) n FROM accessibility_feedback').get()?.n).toBeGreaterThan(0);db.close();
 for(const code of ['en','es','zh','ar','pl','gu','hi']){await visit(page,'/accessibility');await page.locator('.language-control select').selectOption(code);await expect(page.locator('html')).toHaveAttribute('lang',code);await expect(page.locator('h1')).not.toBeEmpty();await page.locator('.desktop-nav a[href="/report"]').click();await expect(page.locator('.time-picker')).toHaveCount(4);const twelve=new Intl.DateTimeFormat(code,{hour:'numeric'}).resolvedOptions().hour12;await expect(page.locator('.time-picker').first().locator('select')).toHaveCount(twelve?3:2);}
});

test('rendered button contrast, simulated color vision and enlarged text retain usable labels',async({page,context})=>{
 await visit(page,'/');
 const button=page.getByRole('button',{name:'Find Care',exact:true});
 const contrast=await button.evaluate(node=>{
  const css=getComputedStyle(node),rgb=(s:string)=>s.match(/\d+(?:\.\d+)?/g)!.slice(0,3).map(Number);
  const lum=(values:number[])=>values.map(v=>{const n=v/255;return n<=.04045?n/12.92:((n+.055)/1.055)**2.4;}).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0);
  const a=lum(rgb(css.color)),b=lum(rgb(css.backgroundColor));return (Math.max(a,b)+.05)/(Math.min(a,b)+.05);
 });expect(contrast).toBeGreaterThanOrEqual(4.5);
 await page.screenshot({path:'test-results/healthcare-homepage.png',fullPage:true});
 await visit(page,'/clinic/brightwell-urgent-care');
 for(const item of await page.locator('.live-number-panel>span,.live-number-panel>strong,.live-number-panel .concept-help summary,.live-number-panel .estimate-evidence p').all()){
  const ratio=await item.evaluate(node=>{
   const parse=(s:string)=>s.match(/\d+(?:\.\d+)?/g)!.map(Number);const fg=parse(getComputedStyle(node).color);let parent:Element|null=node,bg=[255,255,255];
   while(parent){const candidate=parse(getComputedStyle(parent).backgroundColor);if(candidate.length===3||candidate[3]===1){bg=candidate;break;}parent=parent.parentElement;}
   const lum=(values:number[])=>values.slice(0,3).map(v=>{const n=v/255;return n<=.04045?n/12.92:((n+.055)/1.055)**2.4;}).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0);
   const a=lum(fg),b=lum(bg);return (Math.max(a,b)+.05)/(Math.min(a,b)+.05);
  });expect(ratio).toBeGreaterThanOrEqual(4.5);
 }
 const cdp=await context.newCDPSession(page);
 for(const type of ['protanopia','deuteranopia','tritanopia','achromatopsia'] as const){
  await cdp.send('Emulation.setEmulatedVisionDeficiency',{type});
  for(const pair of await page.locator('.stage-pair').all()){await expect(pair.locator('strong')).toBeVisible();await expect(pair.locator('.stage-key')).toBeVisible();}
  await page.locator('.visit-breakdown').screenshot({path:`test-results/healthcare-colors-${type}.png`});
 }await cdp.send('Emulation.setEmulatedVisionDeficiency',{type:'none'});await cdp.detach();
 await visit(page,'/accessibility');
 for(const width of [390,1440]){await page.setViewportSize({width,height:900});const size=await page.evaluate(()=>parseFloat(getComputedStyle(document.body).fontSize));await page.evaluate(()=>document.documentElement.style.fontSize='200%');expect(await page.evaluate(()=>parseFloat(getComputedStyle(document.body).fontSize))).toBe(size*2);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await expect(page.locator('h1')).toBeVisible();await page.evaluate(()=>document.documentElement.style.fontSize='');}
});
test('ready evidence renders contributing counts and localized aging; stale and sparse real estimates are unavailable',async({page})=>{
 const now=Date.now();let state='ready';
 await page.route('**/api/clinics/brightwell-urgent-care',async route=>{
  const response=await route.fetch();const clinic=await response.json();
  clinic.fictional=false;clinic.estimates=clinic.estimates.map((value:any)=>({...value,totalMinutes:47,range:[37,57],evidenceState:state,provenance:{fictional:false,calculatedAt:new Date(now-14*60000).toISOString(),evidenceUpdatedAt:new Date(now-20*60000).toISOString(),sources:state==='ready'?[{kind:'patient-reports',count:10}]:[]}}));
  await route.fulfill({response,json:clinic});
 });
 await page.clock.install({time:now});await visit(page,'/clinic/brightwell-urgent-care');
 await expect(page.locator('.estimate-evidence').first()).toContainText('10 recent patient reports');await expect(page.locator('.estimate-evidence').first()).toContainText('14 minutes ago');await expect(page.locator('.estimate-evidence').first()).not.toContainText('Clinic-provided data');
 await page.clock.fastForward(60000);await expect(page.locator('.estimate-evidence').first()).toContainText('15 minutes ago');
 await page.locator('.language-control select').selectOption('ar');await expect(page.locator('.estimate-evidence').first()).not.toContainText('minutes ago');
 for(const next of ['stale','insufficient']){state=next;await visit(page,'/clinic/brightwell-urgent-care');await expect(page.locator('.live-number-panel > strong')).toContainText('Unavailable');await page.setViewportSize({width:320,height:900});expect(await page.locator('.live-number-panel > strong').evaluate(node=>node.scrollWidth<=node.clientWidth+1)).toBe(true);await expect(page.locator('.visit-breakdown')).toHaveCount(0);await expect(page.locator('.estimate-evidence').first()).toContainText(next==='stale'?'Evidence is stale':'Not enough recent evidence');await expect(page.locator('.estimate-evidence').first()).not.toContainText('Based on:');}
});
