import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {mkdtempSync,readFileSync,readdirSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {createApplication} from '../server/application.ts';
import {openDatabase,writeClinic,backupDatabase} from '../server/database.ts';
import {readConfig,type ServerConfig} from '../server/config.ts';
import {seedDemo} from '../server/seed.ts';
import {estimate,type Evidence} from '../server/estimator.ts';
import {validateDraft} from '../server/validation.ts';
import {initialDraft,validateReport} from '../src/utils/report.ts';
import {poundsToKg,kgToPounds,inchesToCm,cmToInches} from '../src/utils/measurements.ts';
import {clinics} from '../src/data/mockData.ts';
import {searchDirectory} from '../src/services/search.ts';
const defaultSearchFilters={query:'',insurance:'',specialty:'',language:'',minimumRating:0,visitMode:'all' as const,timing:'all' as const,maxDistance:10};
import {accessibilityKeys} from '../src/types.ts';
import {unknownAccessibility} from '../src/utils/accessibility.ts';
function setup(){const root=mkdtempSync(tmpdir()+'/mediq-healthcare-');const config:ServerConfig={...readConfig(),environment:'test',database:root+'/db.sqlite',mailDirectory:root+'/mail',origin:'http://localhost:4173',mailMode:'file',adminEnabled:true};const app=createApplication(config);seedDemo(app.db,config);
 function client(ip='test'){const cookies=new Map<string,string>();return {async call(path:string,method='GET',body?:unknown){const response=await app.handle(new Request(config.origin+'/api'+path,{method,headers:{origin:config.origin,'content-type':'application/json',cookie:[...cookies].map(([k,v])=>k+'='+v).join('; '),'idempotency-key':crypto.randomUUID()},...(method==='GET'?{}:{body:JSON.stringify(body||{})})}),ip);for(const raw of response.headers.getSetCookie()){const pair=raw.split(';')[0],i=pair.indexOf('=');cookies.set(pair.slice(0,i),pair.slice(i+1));}return {status:response.status,data:await response.json() as any};}};}
 async function verified(c:ReturnType<typeof client>,email:string){await c.call('/auth/sign-up/email','POST',{firstName:'Care',lastName:'Tester',email,password:'Healthcare-test-password-2026'});const mail=readdirSync(config.mailDirectory).map(n=>JSON.parse(readFileSync(config.mailDirectory+'/'+n,'utf8'))).find(m=>m.to===email);assert(mail);const result=await c.call('/auth/email-otp/verify-email','POST',{email,otp:mail.otp});assert.equal(result.status,200);return (await c.call('/me')).data;}
 return {app,config,client,verified,close(){app.close();rmSync(root,{recursive:true,force:true});}};}
test('upgrade migration removes gender, preserves exact metric values and prior reports, and marks existing tours complete',async()=>{
 const root=mkdtempSync(tmpdir()+'/mediq-migration-');const config={...readConfig(),environment:'test',database:root+'/db.sqlite'} as ServerConfig;
 const old=new DatabaseSync(config.database);old.exec(readFileSync(new URL('../server/migrations/001_initial.sql',import.meta.url),'utf8'));old.exec('CREATE TABLE migrations(name TEXT PRIMARY KEY,applied_at INTEGER NOT NULL)');old.prepare('INSERT INTO migrations VALUES (?,?)').run('001_initial.sql',Date.now());old.prepare('INSERT INTO environment VALUES (1,?)').run('test');
 old.prepare('INSERT INTO user(id,name,email,emailVerified,createdAt,updatedAt) VALUES (?,?,?,?,?,?)').run('existing','Existing','old@example.test',1,Date.now(),Date.now());old.prepare('INSERT INTO profiles(user_id,gender,weight_kg,height_cm) VALUES (?,?,?,?)').run('existing','must be deleted',70.123456,175.234567);old.prepare('INSERT INTO account_metadata VALUES (?,?)').run('existing',Date.now());old.prepare('INSERT INTO clinics VALUES (?,?,?)').run(clinics[0].id,JSON.stringify({...clinics[0],accessibility:undefined}),Date.now());old.prepare('INSERT INTO reports VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run('existing-report',clinics[0].id,'existing','actor','request','fingerprint','completed-visit','walk-in',45,null,Date.now(),'2026-10-03','accepted','{}');old.close();
 await backupDatabase(config,root+'/before.sqlite');
 const original=new DatabaseSync(config.database,{readOnly:true});assert(original.prepare('PRAGMA table_info(profiles)').all().some(row=>row.name==='gender'));assert.equal(original.prepare('SELECT count(*) n FROM migrations').get()?.n,1);original.close();
 const snapshot=new DatabaseSync(root+'/before.sqlite',{readOnly:true});assert.equal(snapshot.prepare('SELECT gender FROM profiles').get()?.gender,'must be deleted');snapshot.close();await assert.rejects(backupDatabase(config,root+'/before.sqlite'),/never overwritten/);
 const db=openDatabase(config);assert(!db.prepare('PRAGMA table_info(profiles)').all().some(row=>row.name==='gender'));const profile=db.prepare('SELECT * FROM profiles').get()!;assert.equal(profile.weight_kg,70.123456);assert.equal(profile.height_cm,175.234567);assert.equal(db.prepare('SELECT tour_state FROM account_metadata').get()?.tour_state,'complete');assert.equal(db.prepare('SELECT total_minutes FROM reports').get()?.total_minutes,45);assert.equal(db.prepare("SELECT count(*) n FROM clinic_accessibility WHERE availability='unknown'").get()?.n,7);db.close();const reopened=openDatabase(config);assert.equal(reopened.prepare('SELECT count(*) n FROM migrations').get()?.n,2);reopened.close();rmSync(root,{recursive:true,force:true});
});
test('tri-state accessibility filters are hard constraints in service and API, alongside all existing filters',async()=>{const h=setup();try{const c=h.client();for(const key of accessibilityKeys){const results=searchDirectory(clinics,{...defaultSearchFilters,accessibility:[key]});assert(results.length);assert(results.every(clinic=>clinic.accessibility?.[key]==='available'));const remote=await c.call('/clinics?filters='+encodeURIComponent(JSON.stringify({...defaultSearchFilters,accessibility:[key]})));assert.equal(remote.status,200);assert.deepEqual(remote.data.map((x:any)=>x.id),results.map(x=>x.id));}const unknown={...clinics[0],accessibility:unknownAccessibility()};assert.equal(searchDirectory([unknown],{...defaultSearchFilters,accessibility:['wheelchair']}).length,0);const combined=searchDirectory(clinics,{...defaultSearchFilters,accessibility:['wheelchair','restroom'],insurance:'Medicaid',language:'Polish',visitMode:'walk-in',maxDistance:3});assert.equal(combined.length,1);assert.equal(combined[0].id,clinics[0].id);assert.equal(searchDirectory(clinics,{...defaultSearchFilters,accessibility:['wheelchair'],specialty:'Pediatrics'}).length,0);assert.equal((await c.call('/clinics?filters='+encodeURIComponent(JSON.stringify({accessibility:['invented']})))).status,400);}finally{h.close();}});
test('provenance uses retained report inputs, never ongoing waits or excluded outliers, and keeps stale/sparse honest',async()=>{const now=Date.now();const report=(total:number,age:number,kind='completed-visit'):Evidence=>({kind,total_minutes:kind==='completed-visit'?total:null,elapsed_minutes:kind==='current-wait'?total:null,status:'accepted',submitted_at:now-age});const evidence=[report(45,1000),report(46,2000),report(44,3000),report(900,4000),report(99,100,'current-wait')];const result=estimate(evidence,now);assert.equal(result.state,'ready');assert.deepEqual(result.sources,[{kind:'patient-reports',count:3}]);assert.equal(result.evidenceUpdatedAt,new Date(now-1000).toISOString());assert.equal(result.excludedOutliers,1);assert.equal(result.ongoingCount,1);assert.equal(estimate([report(30,1000)],now).state,'insufficient');const stale=estimate([report(30,2*86400000),report(31,3*86400000),report(32,4*86400000)],now);assert.equal(stale.state,'stale');assert.deepEqual(stale.sources,[]);const h=setup();try{const c=h.client();const fixture=(await c.call('/clinics/'+clinics[0].id)).data.estimates[0];assert.equal(fixture.evidenceState,'insufficient');assert.equal(fixture.provenance.fictional,true);assert.deepEqual(fixture.provenance.sources,[{kind:'fictional-model'}]);writeClinic(h.app.db,{...clinics[0],id:'real-clinic',fictional:false,providers:[]},false);const real=(await c.call('/clinics/real-clinic')).data.estimates[0];assert.equal(real.provenance.fictional,false);assert.deepEqual(real.provenance.sources,[]);
 const day=new Date(Date.now()-86400000).toISOString().slice(0,10);
 for(const totalRange of ['30–60 minutes','60–90 minutes','90–120 minutes'])assert.equal((await c.call('/reports','POST',{...initialDraft('real-clinic'),visitDate:day,visitMode:'walk-in',totalRange})).status,201);
 const ready=(await c.call('/clinics/real-clinic')).data.estimates.find((value:any)=>value.mode==='walk-in');assert.equal(ready.totalMinutes,75);assert.equal(ready.evidenceState,'ready');assert.equal(ready.provenance.fictional,false);assert.deepEqual(ready.provenance.sources,[{kind:'patient-reports',count:3}]);assert.equal(ready.provenance.evidenceUpdatedAt,new Date(Number(h.app.db.prepare("SELECT max(submitted_at) n FROM reports WHERE clinic_id='real-clinic'").get()?.n)).toISOString());}finally{h.close();}});
test('midnight validation, optional unknown details and unknown mode remain null end to end; ongoing is separate',async()=>{const h=setup();try{const c=h.client();const date=new Date(Date.now()-2*86400000).toISOString().slice(0,10);const draft={...initialDraft(clinics[0].id),visitDate:date,arrivalTime:'23:30',departureTime:'00:30',crossesMidnight:true};assert.deepEqual(validateReport(draft,'exact'),{});const accepted=await c.call('/reports','POST',draft);assert.equal(accepted.status,201,JSON.stringify(accepted));assert.equal(accepted.data.totalMinutes,60);assert.equal(accepted.data.visitMode,null);
 const dayLong={...draft,visitDate:new Date(Date.now()-3*86400000).toISOString().slice(0,10),departureTime:'23:30'};assert.deepEqual(validateReport(dayLong,'exact'),{});const long=await c.call('/reports','POST',dayLong);assert.equal(long.status,201);assert.equal(long.data.totalMinutes,1440);assert.equal(long.data.moderationStatus,'review');
 const timezoneDraft={...initialDraft(clinics[0].id),timezoneOffsetMinutes:-600,visitDate:'2026-10-05',arrivalTime:'08:00',departureTime:'09:00',insurance:'',language:'',providerId:''};const timezone=validateDraft(timezoneDraft,clinics[0],Date.parse('2026-10-04T23:50:00Z'));assert.equal(timezone.total,60);assert.equal(timezone.draft.insurance,null);assert.equal(timezone.draft.language,null);assert.equal(timezone.draft.providerId,null);assert.equal(h.app.db.prepare('SELECT mode FROM reports WHERE id=?').get(accepted.data.id)?.mode,null);assert(!('communication' in accepted.data));assert(!('providerId' in accepted.data));const wrong=await c.call('/reports','POST',{...draft,crossesMidnight:false});assert.equal(wrong.status,400);assert(validateReport({...draft,providerTime:'23:00'},'exact').times);assert.equal((await c.call('/reports','POST',{...draft,visitDate:'2999-01-01'})).status,400);const ongoing=await c.call('/reports','POST',{...initialDraft(clinics[0].id),visitMode:'walk-in',reportKind:'current-wait',elapsedMinutes:12});assert.equal(ongoing.status,201);assert.equal(h.app.db.prepare('SELECT total_minutes FROM reports WHERE id=?').get(ongoing.data.id)?.total_minutes,null);assert.equal((await c.call('/clinics/'+clinics[0].id)).data.estimates[0].evidenceState,'insufficient');}finally{h.close();}});
test('verified signup starts tour exactly once across devices; completion persists; canonical measurements round-trip without drift',async()=>{const h=setup();try{const a=h.client('first');const me=await h.verified(a,'new@example.test');assert(me.user);assert.equal(me.tourState,'pending');assert.deepEqual((await a.call('/tour/start','POST')).data,{start:true});assert.deepEqual((await a.call('/tour/start','POST')).data,{start:false});assert.equal((await a.call('/tour/complete','POST')).status,200);const b=h.client('device');await b.call('/auth/sign-in/email','POST',{email:'new@example.test',password:'Healthcare-test-password-2026'});assert.equal((await b.call('/me')).data.tourState,'complete');assert.equal((await b.call('/tour/start','POST')).data.start,false);const profile={firstName:'Care',lastName:'Tester',sex:null,weightKg:poundsToKg(154),heightCm:inchesToCm(69),age:null,language:'en',notifications:false};assert.equal((await a.call('/profile','PUT',profile)).status,200);for(let i=0;i<4;i++){const current=(await a.call('/me')).data.profile;assert.equal(current.weightKg,profile.weightKg);assert.equal(current.heightCm,profile.heightCm);assert.equal((await a.call('/profile','PUT',{...current,firstName:'Care',lastName:'Tester'})).status,200);}assert.equal((await a.call('/profile','PUT',{...profile,gender:'hidden'})).status,400);assert(Math.abs(kgToPounds(poundsToKg(154))-154)<1e-10);assert(Math.abs(cmToInches(inchesToCm(69))-69)<1e-10);assert.equal((await h.client('guest').call('/tour/start','POST')).status,401);}finally{h.close();}});
test('accessibility feedback is persisted and administrator-only; clinic accessibility corrections are validated and audited',async()=>{const h=setup();try{const guest=h.client('feedback');assert.equal((await guest.call('/accessibility-feedback','POST',{message:'The care button is difficult to reach with my keyboard.'})).status,201);assert.equal((await guest.call('/admin/accessibility-feedback')).status,401);const admin=h.client('admin');const me=await h.verified(admin,'admin@example.test');h.app.db.prepare('INSERT INTO administrators VALUES (?,?)').run(me.user.id,Date.now());assert.equal((await admin.call('/admin/accessibility-feedback')).data.length,1);const attributes={...unknownAccessibility(),wheelchair:'available'};assert.equal((await admin.call('/admin/clinics/'+clinics[0].id,'PATCH',{accessibility:attributes})).status,200);assert.equal((await guest.call('/clinics/'+clinics[0].id)).data.accessibility.wheelchair,'available');assert.equal(h.app.db.prepare('SELECT count(*) n FROM audit_log').get()?.n,1);assert.equal((await admin.call('/admin/clinics/'+clinics[0].id,'PATCH',{accessibility:{wheelchair:true}})).status,400);assert.equal((await admin.call('/admin/checklist')).data.length,16);}finally{h.close();}});
