import { useEffect,useRef,useState,type FormEvent } from 'react';
import { useApp } from '../context/AppContext';
import { api,errorKey } from '../services/api';
import type { Clinic } from '../types';
interface Directory {accounts:{id:string;firstName:string;lastName:string;email:string;createdAt:number;verifiedAt:number;status:string}[];total:number;pageSize:number;}
interface Metrics {asOf:string;verifiedAccounts:number;activeAccounts:number;accountSessions:number;guestSessions:number;metrics:{metric:string;allTime:number;recent:number}[];jobs:{job:string;status:string;finished_at:number|null;error_code:string|null}[];}
interface Task {id:string;title:string;why:string;action:string;verification:string;status:string;notes:string;guide:string;}
interface Review {id:string;clinic_id:string;kind:string;mode:string;total_minutes:number|null;elapsed_minutes:number|null;status:string;}
interface Audit {action:string;target:string;changes:string;created_at:number;}
const metricLabels:Record<string,string>={verified_signups:'Verified signups',deleted_accounts:'Deleted accounts',saved_plans:'Saved visit plans',reports_ongoing:'Accepted ongoing reports',reports_completed:'Accepted completed reports',reports_review:'Reports flagged for review',report_rejections:'Report rejections',service_failures:'Service failures',job_failures:'Job failures',email_failures:'Email failures'};
export default function AdminPage(){
 const {isAdmin,t,user,language}=useApp();const [tab,setTab]=useState('activity');const [query,setQuery]=useState('');const [page,setPage]=useState(0);const [revision,setRevision]=useState(0);const [error,setError]=useState('');const [loading,setLoading]=useState(true);
 const [directory,setDirectory]=useState<Directory|null>(null);const [metrics,setMetrics]=useState<Metrics|null>(null);const [tasks,setTasks]=useState<Task[]>([]);const [reports,setReports]=useState<Review[]>([]);const [audit,setAudit]=useState<Audit[]>([]);
 const sequence=useRef(0);const refresh=()=>setRevision(r=>r+1);
 useEffect(()=>{if(!isAdmin)return;const timer=setInterval(refresh,30000);return()=>clearInterval(timer);},[isAdmin]);
 useEffect(()=>{
  const id=++sequence.current;if(!isAdmin)return;setLoading(true);setError('');
  const read=async()=>{try{if(tab==='accounts'){const data=await api<Directory>(`/admin/accounts?q=${encodeURIComponent(query)}&page=${page}`);if(id===sequence.current)setDirectory(data);}else if(tab==='activity'){const data=await api<Metrics>('/admin/metrics');if(id===sequence.current)setMetrics(data);}else if(tab==='checklist'){const data=await api<Task[]>('/admin/checklist');if(id===sequence.current)setTasks(data);}else if(tab==='reports'){const data=await api<Review[]>('/admin/reports');if(id===sequence.current)setReports(data);}else if(tab==='audit'){const data=await api<Audit[]>('/admin/audit');if(id===sequence.current)setAudit(data);}}catch(e){if(id===sequence.current)setError(errorKey(e));}finally{if(id===sequence.current)setLoading(false);}};
  void read();return()=>{sequence.current++;};
 },[tab,query,page,revision,isAdmin,user?.id]);
 if(!isAdmin)return <div className="shell page-space"><h1>{t('Access restricted')}</h1><p>{t('You do not have access to this page.')}</p></div>;
 const date=(value:number|string)=>new Intl.DateTimeFormat(language,{dateStyle:'medium',timeStyle:'short',timeZone:'UTC'}).format(new Date(value));
 return <div className="shell page-space admin-shell"><div className="page-heading"><div><span className="eyebrow">{t('Internal · staging only')}</span><h1>{t('Administration')}</h1><p>{t('Refreshes every 30 seconds. All timestamps use UTC.')}</p></div><button className="button button-secondary" onClick={refresh}>{t('Refresh')}</button></div>
  <nav className="admin-tabs" aria-label={t('Administration')}>{[['activity','Activity'],['accounts','Accounts'],['reports','Report review'],['clinics','Clinic corrections'],['checklist','Launch checklist'],['audit','Audit trail']].map(([value,label])=><button className={tab===value?'active':''} aria-pressed={tab===value} key={value} onClick={()=>setTab(value)}>{t(label)}</button>)}</nav>
  {error&&<p role="alert" className="form-error">{t(error)} <button onClick={refresh}>{t('Try again')}</button></p>}{loading&&<p role="status">{t('Please wait…')}</p>}
  {tab==='accounts'&&<><label className="field-label"><span>{t('Search accounts')}</span><input value={query} onChange={e=>{setPage(0);setQuery(e.target.value);}} /></label><p>{t('Verified accounts: {count}',{count:directory?.total||0})}</p><div className="table-scroll"><table><thead><tr>{['Name','Email','Created','Verified','Status'].map(label=><th key={label}>{t(label)}</th>)}</tr></thead><tbody>{directory?.accounts.map(a=><tr key={a.id}><td>{a.firstName} {a.lastName}</td><td>{a.email}</td><td>{date(a.createdAt)}</td><td>{date(a.verifiedAt)}</td><td>{t('Verified')}</td></tr>)}</tbody></table></div><div className="account-links"><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>{t('Back')}</button><span>{t('Page {page}',{page:page+1})}</span><button disabled={!directory||(page+1)*directory.pageSize>=directory.total} onClick={()=>setPage(p=>p+1)}>{t('Next')}</button></div></>}
  {tab==='activity'&&metrics&&<><div className="metric-grid">{[['Verified accounts',metrics.verifiedAccounts],['Active accounts',metrics.activeAccounts],['Account sessions',metrics.accountSessions],['Guest sessions',metrics.guestSessions]].map(([label,value])=><article className="account-card" key={label}><h2>{t(String(label))}</h2><strong>{new Intl.NumberFormat(language).format(Number(value))}</strong></article>)}</div><p>{t('Active means a visible session with interaction in the last 5 minutes. Sessions are not people.')}</p><p>{t('Recent means 7 UTC calendar days including today. Counts are deduplicated stored events; reopening a page does not create a visit plan or report.')}</p><p>{t('Confirmed bookings are unavailable. Saved visit plans are not bookings.')}</p><div className="table-scroll"><table><thead><tr><th>{t('Metric')}</th><th>{t('Recent')}</th><th>{t('All time')}</th></tr></thead><tbody>{Object.entries(metricLabels).map(([key,label])=>{const m=metrics.metrics.find(v=>v.metric===key);return <tr key={key}><td>{t(label)}</td><td>{m?.recent||0}</td><td>{m?.allTime||0}</td></tr>;})}</tbody></table></div><h2>{t('Recent jobs')}</h2><ul>{metrics.jobs.map((job,i)=><li key={i}>{t(job.job)} · {t(job.status)} · {job.finished_at?date(job.finished_at):t('Running')}</li>)}</ul></>}
  {tab==='checklist'&&tasks.map(task=><TaskCard key={task.id} task={task} onSaved={refresh}/>)}
  {tab==='reports'&&<>{!reports.length&&<p>{t('No reports need review.')}</p>}{reports.map(report=><ReviewCard key={report.id} report={report} onSaved={refresh}/>)}</>}
  {tab==='clinics'&&<ClinicCorrection/>}
  {tab==='audit'&&<div className="table-scroll"><table><thead><tr><th>{t('Action')}</th><th>{t('Record')}</th><th>{t('Changes')}</th><th>{t('Time (UTC)')}</th></tr></thead><tbody>{audit.map((item,i)=><tr key={i}><td>{t(item.action)}</td><td>{item.target}</td><td><pre>{item.changes}</pre></td><td>{date(item.created_at)}</td></tr>)}</tbody></table></div>}
 </div>;
}
function TaskCard({task,onSaved}:{task:Task;onSaved:()=>void}){
 const {t}=useApp();const [status,setStatus]=useState(task.status);const [notes,setNotes]=useState(task.notes);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const save=async(e:FormEvent)=>{e.preventDefault();if(busy)return;setBusy(true);try{await api(`/admin/checklist/${task.id}`,'PUT',{status,notes});setError('');onSaved();}catch(e){setError(errorKey(e));}finally{setBusy(false);}};
 return <form className="account-card account-form" onSubmit={save}><h2>{t(task.title)}</h2><p>{t(task.why)}</p><p><strong>{t('Action')}: </strong>{t(task.action)}</p><p><strong>{t('Verify completion')}: </strong>{t(task.verification)}</p><a href="/api/admin/guide" target="_blank" rel="noreferrer">{t('Setup guide')}</a><label className="field-label"><span>{t('Status')}</span><select value={status} onChange={e=>setStatus(e.target.value)}>{['todo','doing','done'].map(value=><option key={value} value={value}>{t(value)}</option>)}</select></label><label className="field-label"><span>{t('Notes')}</span><textarea maxLength={2000} value={notes} onChange={e=>setNotes(e.target.value)} /></label>{error&&<p role="alert">{t(error)}</p>}<button disabled={busy} className="button button-secondary">{t('Save changes')}</button></form>;
}
function ReviewCard({report,onSaved}:{report:Review;onSaved:()=>void}){
 const {t}=useApp();const [reason,setReason]=useState('');const [status,setStatus]=useState('accepted');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const save=async(e:FormEvent)=>{e.preventDefault();if(busy)return;setBusy(true);try{await api(`/admin/reports/${report.id}`,'PUT',{status,reason});onSaved();}catch(e){setError(errorKey(e));}finally{setBusy(false);}};
 return <form className="account-card account-form" onSubmit={save}><h2>{report.clinic_id}</h2><p>{t(report.kind)} · {t(report.mode)} · {report.total_minutes??report.elapsed_minutes} {t('min')}</p><label className="field-label"><span>{t('Decision')}</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="accepted">{t('Accept')}</option><option value="rejected">{t('Reject')}</option></select></label><label className="field-label"><span>{t('Reason')}</span><input required minLength={3} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)} /></label>{error&&<p role="alert">{t(error)}</p>}<button disabled={busy} className="button button-secondary">{t('Save decision')}</button></form>;
}
function ClinicCorrection(){
 const {t}=useApp();const [clinics,setClinics]=useState<Clinic[]>([]);const [id,setId]=useState('');const [correction,setCorrection]=useState('{}');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
 useEffect(()=>{let active=true;void api<Clinic[]>('/clinics').then(data=>{if(active)setClinics(data);},e=>{if(active)setError(errorKey(e));});return()=>{active=false;};},[]);
 const select=(next:string)=>{setId(next);const c=clinics.find(c=>c.id===next);setCorrection(JSON.stringify(c?{name:c.name,address:c.address,phone:c.phone,status:c.status,languages:c.languages,insurance:c.insurance,specialties:c.specialties,symptoms:c.symptoms}:{},null,2));};
 const save=async(e:FormEvent)=>{e.preventDefault();if(busy)return;setBusy(true);setError('');setMessage('');try{const changed=await api<Clinic>(`/admin/clinics/${id}`,'PATCH',JSON.parse(correction));setClinics(current=>current.map(c=>c.id===id?changed:c));setMessage('Changes saved with an audit record.');}catch(e){setError(e instanceof SyntaxError?'Enter valid JSON.':errorKey(e));}finally{setBusy(false);}};
 return <form className="account-card account-form" onSubmit={save}><h2>{t('Clinic corrections')}</h2><label className="field-label"><span>{t('Clinic')}</span><select required value={id} onChange={e=>select(e.target.value)}><option value="">{t('Choose a clinic')}</option>{clinics.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="field-label"><span>{t('Directory fields (JSON)')}</span><textarea className="code-editor" rows={15} value={correction} onChange={e=>setCorrection(e.target.value)} /></label><p>{t('Only approved directory fields can be changed. Every correction is audited.')}</p>{error&&<p role="alert">{t(error)}</p>}{message&&<p role="status">{t(message)}</p>}<button disabled={busy||!id} className="button button-primary">{t('Save changes')}</button></form>;
}
